name: BMYBBS Content Parser CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: NODE_OPTIONS=--experimental-vm-modules npm run test
      - name: Upload coverage report
        run: cat coverage/lcov.info | COVERALLS_REPO_TOKEN=$TOKEN node_modules/coveralls/bin/coveralls.js
        env:
          TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

